import { Container, Header } from "@/styles/layout";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../../public/globals.css";
import Image from "next/image";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Container>
					<Header>
						<Image alt="" src="/assets/logo.svg" width={56} height={56} />
						Ignite shop
					</Header>
					{children}
				</Container>
			</body>
		</html>
	);
}
